#!/bin/bash


androidSRC="/home/usr/android" # android源码的根目录
packageSRC="packages/apps/Launcher2" # 要编译项目的源码目录
outSRC="out/target/product/rk30sdk/system/app/Launcher2.apk" # 编译产物的保存路径

isLastCommandSuccess() {
    test $? != 0 && exit 1
}

cd $androidSRC
isLastCommandSuccess

# 准备好编译命令，如mmm
which mmm
if [ $? != 0 ];
then
echo "prepare the compiling evironment..."
source build/envsetup.sh > /dev/null
isLastCommandSuccess
else
:
fi

echo "begin to compile..."
mmm $packageSRC
isLastCommandSuccess

# 检查adb是否是以root运行，如果不是，以root权限重新启动adb
ps -u 0 | grep " adb"
if [ $? != 0 ];
then
echo "restarting adb on root privilege"
adb kill-server
isLastCommandSuccess
sudo adb start-server
isLastCommandSuccess
echo "adb restarted"
else
:
fi

echo "begin to push the compiled result..."
adb push $outSRC /system/app 2>&1 | grep "Read-only file system"
if [ $? = 0 ];
then
adb remount
adb push $outSRC /system/app
else
:
fi
isLastCommandSuccess
echo "finish pushing."

echo "done"
